//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAS.Tasks.CatalogFormats {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Translate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SAS.Tasks.CatalogFormats.Translate", typeof(Translate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format definition: {0} in {1}.{2}.
        /// </summary>
        internal static string LabelFormatDefinition {
            get {
                return ResourceManager.GetString("LabelFormatDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-defined formats.
        /// </summary>
        internal static string LabelUserDefinedFormats {
            get {
                return ResourceManager.GetString("LabelUserDefinedFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog {1}.{2} contains {0} entries.
        /// </summary>
        internal static string MessageCatalog {
            get {
                return ResourceManager.GetString("MessageCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} was deleted..
        /// </summary>
        internal static string MessageCatalogDeleted {
            get {
                return ResourceManager.GetString("MessageCatalogDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0} WAS NOT deleted..
        /// </summary>
        internal static string MessageCatalogNotDeleted {
            get {
                return ResourceManager.GetString("MessageCatalogNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading catalog entry: {0} - {1}.
        /// </summary>
        internal static string MessageCatalogReadError {
            get {
                return ResourceManager.GetString("MessageCatalogReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure that you want to delete {0}?.
        /// </summary>
        internal static string MessageDeleteConfirm {
            get {
                return ResourceManager.GetString("MessageDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Could not generate format definition.
        /// </summary>
        internal static string MessageErrorFormat {
            get {
                return ResourceManager.GetString("MessageErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search locations: {0}.
        /// </summary>
        internal static string MessageFmtSearch {
            get {
                return ResourceManager.GetString("MessageFmtSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library contains {0} catalogs.
        /// </summary>
        internal static string MessageLibrary {
            get {
                return ResourceManager.GetString("MessageLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server has {0} libraries defined.
        /// </summary>
        internal static string MessageServer {
            get {
                return ResourceManager.GetString("MessageServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SAS server &apos;{0}&apos; is busy. Cannot generate the format definition..
        /// </summary>
        internal static string MessageServerBusy {
            get {
                return ResourceManager.GetString("MessageServerBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm: Delete entry?.
        /// </summary>
        internal static string TitleDeleteConfirm {
            get {
                return ResourceManager.GetString("TitleDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string TitleError {
            get {
                return ResourceManager.GetString("TitleError", resourceCulture);
            }
        }
    }
}
